// Generated by CoffeeScript 1.9.0
var __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
  __hasProp = {}.hasOwnProperty;

window.App = (function(_super) {
  __extends(App, _super);

  function App() {
    return App.__super__.constructor.apply(this, arguments);
  }

  App.prototype.initialize = function() {
    var deck;
    this.set('deck', deck = new Deck());
    this.set('playerHand', deck.dealPlayer());
    this.set('dealerHand', deck.dealDealer());
    return (this.get('playerHand')).on("change:bust", (function(_this) {
      return function() {
        return _this.assignWinner();
      };
    })(this));
  };

  App.prototype.stand = function() {
    console.log('hi');
    return this.dealerTurn();
  };

  App.prototype.dealerTurn = function() {
    return this.get('dealerHand'.play());
  };

  App.prototype.assignWinner = function() {
    if ((this.get('playerHand')).busted()) {
      return this.playerBust();
    }
  };

  App.prototype.playerBust = function() {
    return this.endRound();
  };

  App.prototype.endRound = function() {
    return this.trigger('change:end');
  };

  return App;

})(Backbone.Model);
